yegor256/awesome-cfp

requirements.txt

`pip freeze > requirements.txt`

Lock transitive dependencies

---

.github/workflows/tests.yml
.gitignore
compile.py
test_compile.py

#45 integrate pytest

---

.github/workflows/tests.yml
compile.py
setup.cfg

Wemake python styldeguide in workflow

---

compile.py
fixtures/simple/README.md
fixtures/simple/expected.md

#34 render dates

---

compile.py
fixtures/few_rows/README.md
fixtures/few_rows/expected.md
fixtures/few_rows/input.yml

Fix empty lines between rows

---

compile.py
fixtures/few_rows/README.md
fixtures/few_rows/expected.md
fixtures/null-cfp/README.md
fixtures/null-cfp/expected.md
fixtures/null-cfp/input.yml

Handle null cfp column

---

compile.py
requirements.txt
test_compile.py
tests.sh

13 validate links

---

.github/workflows/tests.yml
compile.py
requirements.txt
test_compile.py

#10 check expired cfp

---

cfp.yml
compile.py
fixtures/empty-cells/input.yml
fixtures/few_rows/input.yml
fixtures/null-cfp/input.yml
fixtures/simple/input.yml

Change `cfp.yml` format

---

compile.py
fixtures/few_rows/expected.md
fixtures/table-sorting/README.md
fixtures/table-sorting/expected.md
fixtures/table-sorting/input.yml

Sort records for md table

---

test_compile.py

Mock http for test expired cfp

---

.rultor.yml

Run pytest executable script from binary dir

---

.github/workflows/py-lint.yml

Repository [archieved](https://github.com/cclauss/GitHub-Action-for-pylint/commit/3dcbcd675a67488741844c76f18f40e0b64dd980)

Remove GitHub-Action-for-pylint using

---

cfp.yml

#140 add EASE'25

---

cfp.yml

#140 add ICFP'25

---

cfp.yml

@yegor256 hello, please take a look

#140 add ISSRE'25

---

cfp.yml

#140 add SEAA'25

---

cfp.yml

#140 add APLAS'25 only

---

cfp.yml

#140 add ICSME'25

---

cfp.yml
compile.py
fixtures/empty-cells/input.yml
fixtures/few_rows/input.yml
fixtures/later_conf/README.md
fixtures/later_conf/expected.md
fixtures/later_conf/input.yml
fixtures/null-cfp/input.yml
fixtures/simple/input.yml
fixtures/update-expired-date/input.yml
test_compile.py

`later: true` flag

---

.github/workflows/py-lint.yml

ref: https://github.com/wemake-services/wemake-python-styleguide/releases/tag/1.0.0

Update lint action

---

cfp.yml

this PR fixes issue #90

---

cfp.yml

Add ECOOP 2025
